### ISSUE TITLE
ValueError: You must provide either a `model` or `model_data` to create a model

### ISSUE THREAD

**Issue by pradeepdev-1995** [philschmid/cdk-samples#1]
I tried to Bootstrap my application in the cloud using the command, 
**cdk bootstrap**
I am following the steps specified in the official documentation([[https://github.com/philschmid/cdk-samples/tree/master/sagemaker-serverless-huggingface-endpoint](https://github.com/philschmid/cdk-samples/tree/master/sagemaker-serverless-huggingface-endpoint)])

But it shows the error like this

```
raise ValueError("You must provide either a `model` or `model_data` to create a model")
ValueError: You must provide either a `model` or `model_data` to create a model
```

Attaching the screenshot
![Screenshot from 2021-12-17 16-57-09](https://user-images.githubusercontent.com/41164884/146538060-ae795bf3-1f8e-41c5-a981-b07e7750830e.png)

**Comment by philschmid** [comment]
Hey @pradeepdev-1995,

thanks for opening the issue! I thought you can run `cdk bootstrap` without providing the context. To fix this just run 
```
cdk bootstrap \
   -c model="distilbert-base-uncased-finetuned-sst-2-english" \
   -c task="text-classification"
```
this should do the trick. I ll fix the documentation

**Comment by pradeepdev-1995** [comment]
@philschmid  Thanks for the update.
I will check it. Instead of a pre-trained model(distilbert-base-uncased-finetuned-sst-2-english), if we want to bootstrap with a fine-tuned model which is in our local machine, what will be the procedure?
Shall we replace the model name in the above code with the local fine-tuned model path?

**Comment by philschmid** [comment]
No, i think it is fine. You need to bootstrap only once. And for deploy you need to change the context to model you want to use.

**Comment by pradeepdev-1995** [comment]
@philschmid 
So is this the way you are mentioning?

For bootstrapping
```
cdk bootstrap \
   -c model="distilbert-base-uncased-finetuned-sst-2-english" \
   -c task="text-classification"
Deploy your Hugging Face Transformer model to Amazon SageMaker
```
For deploying a fine-tuned model from local
```
cdk deploy \
   -c model=<Fine tuned model path> \
   -c task="text-classification"
```

**Comment by moshonkel** [comment]
How did you solve this issue ?

**Comment by ghost** [comment]
Hey, i dont understand where our fine tuned model is supposed to be?

I am trying to deploy a model.tar.gz from s3

```
DESKTOP-SMI7P0D ~/github/hf_deploy_test/cdk-samples/sagemaker-serverless-huggingface-endpoint ‹master*›

╰─$ cdk deploy \                                                                                                                                                                                              -c model_data="s3://test-model-data/model.tar.gz" \
-c task="feature-extraction"`
```

Is this correct? I am getting an error, that the sagemaker role cant access the s3 bucket?

```
8:40:26 PM | CREATE_FAILED        | AWS::SageMaker::Model          | SagemakerEndpointhfmodel2DC32936
Could not access model data at s3://test-model-data/model.tar.gz. Please ensure that the role "arn:aws:iam::232372787505:role/HuggingfaceServerlessSage-hfsagemakerexecutionrole-R8V0WN8IWG0P" exists and that
its trust relationship policy allows the action "sts:AssumeRole" for the service principal "sagemaker.amazonaws.com". Also ensure that the role has "s3:GetObject" permissions and that the object is located in
eu-central-1. (Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: b1514dbe-df86-4b90-bea6-f2c278ed766f; Proxy: null)
```

**Comment by philschmid** [comment]
Hey @moshonkel, 

the sample currenlty supports deploying models from hf.co/models to SageMaker. If you want to use your own `model.tar.gz` you would need to adjust https://github.com/philschmid/cdk-samples/blob/b3c85cf6cdd1b95a5e5929a3f62296b7bf5c0b77/sagemaker-serverless-huggingface-endpoint/huggingface_sagemaker/sagemaker_endpoint.py#L71
there you would need to add `model_data_url` [[documentation](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_sagemaker/CfnModel.html)]. Not sure which other changes would be required.

**Comment by jannostudio** [comment]
Sorry for the late reply, but i had to read a bunch to understand how doing anything with the aws cdk actually works. 

I now store my model on s3 

and gave the role you created additional access to an s3 bucket 

` 
        execution_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "s3:GetObject",
                ],
                resources=[
                    "arn:aws:s3:::test-model-data/model.tar.gz",
                ],
            )
        )`

Which shouldnt be necessary, because the created role already has s3 access, right?
I am always getting this error:

```
8:45:30 AM | CREATE_FAILED        | AWS::SageMaker::Model          | SagemakerEndpointhfmodel2DC32936
Could not access model data at https://test-model-data.s3.eu-central-1.amazonaws.com/model.tar.gz. Please ensure that the role "arn:aws
:iam::232372787505:role/HuggingfaceSagemakerEndpo-hfsagemakerexecutionrole-1IC9I6H5ENCWA" exists and that its trust relationship policy a
llows the action "sts:AssumeRole" for the service principal "sagemaker.amazonaws.com". Also ensure that the role has "s3:GetObject" permi
ssions and that the object is located in eu-central-1. (Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Requ
est ID: b550f2ef-24e8-40be-8953-a05bb871178d; Proxy: null)
```



The bucket and its content have been created by hand, could this be an issue?

Edit: The code above was correct, but i put it after creating the endpoint in the stack, now, that the order is correct it works.

I dont really understand why i have to give specific access to the s3 bucket, but it is what it is.
