### ISSUE TITLE
models >512 mb

### ISSUE THREAD

**Issue by jannostudio** [philschmid/cdk-samples#3]
Hey ive read that you have to set an environment variable to fix the error with models >512 mb (MMS_DEFAULT_WORKERS_PER_MODEL=1). What do i have to change in your cdk (serverless) example to accomplish this?

Thanks in advance

**Comment by philschmid** [comment]
Hey i just pushed a change to master for that [[REF](https://github.com/philschmid/cdk-samples/blob/ff422c0b6617c7d84e9f8ae1371d6c4cf8c39a25/sagemaker-serverless-huggingface-endpoint/huggingface_sagemaker/sagemaker_endpoint.py#L63)]
Could you re-pull and re-try it?

**Comment by jannostudio** [comment]
Works like a Charm, thanks a lot again!
